// This file will be auto-generated by Supabase CLI
// For now, we define a basic type

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      nuzlocke_runs: {
        Row: {
          id: string
          user_id: string
          run_name: string
          game_mode: 'classic' | 'complete' | 'radical'
          is_active: boolean
          selected_rules: Json
          total_captures: number
          total_deaths: number
          gyms_defeated: number
          revival_tokens_available: number
          created_at: string
          completed_at: string | null
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          run_name: string
          game_mode: 'classic' | 'complete' | 'radical'
          is_active?: boolean
          selected_rules?: Json
          total_captures?: number
          total_deaths?: number
          gyms_defeated?: number
          revival_tokens_available?: number
          created_at?: string
          completed_at?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          run_name?: string
          game_mode?: 'classic' | 'complete' | 'radical'
          is_active?: boolean
          selected_rules?: Json
          total_captures?: number
          total_deaths?: number
          gyms_defeated?: number
          revival_tokens_available?: number
          created_at?: string
          completed_at?: string | null
          updated_at?: string
        }
      }
      encounters: {
        Row: {
          id: string
          run_id: string
          route_id: string
          route_name: string
          pokemon_name: string
          pokemon_level: number
          nickname: string | null
          status: 'alive' | 'dead' | 'boxed'
          acquisition_method: 'wild' | 'gift' | 'trade'
          is_in_team: boolean
          team_position: number | null
          is_shiny: boolean
          nature: string | null
          ability: string | null
          notes: string | null
          caught_at: string
          died_at: string | null
          was_revived: boolean
          revival_date: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          run_id: string
          route_id: string
          route_name: string
          pokemon_name: string
          pokemon_level: number
          nickname?: string | null
          status?: 'alive' | 'dead' | 'boxed'
          acquisition_method?: 'wild' | 'gift' | 'trade'
          is_in_team?: boolean
          team_position?: number | null
          is_shiny?: boolean
          nature?: string | null
          ability?: string | null
          notes?: string | null
          caught_at?: string
          died_at?: string | null
          was_revived?: boolean
          revival_date?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          run_id?: string
          route_id?: string
          route_name?: string
          pokemon_name?: string
          pokemon_level?: number
          nickname?: string | null
          status?: 'alive' | 'dead' | 'boxed'
          acquisition_method?: 'wild' | 'gift' | 'trade'
          is_in_team?: boolean
          team_position?: number | null
          is_shiny?: boolean
          nature?: string | null
          ability?: string | null
          notes?: string | null
          caught_at?: string
          died_at?: string | null
          was_revived?: boolean
          revival_date?: string | null
          updated_at?: string
        }
      }
      gym_battles: {
        Row: {
          id: string
          run_id: string
          gym_number: number
          leader_name: string
          variant_used: string | null
          status: 'pending' | 'won' | 'lost'
          casualties: number
          attempts: number
          notes: string | null
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          run_id: string
          gym_number: number
          leader_name: string
          variant_used?: string | null
          status?: 'pending' | 'won' | 'lost'
          casualties?: number
          attempts?: number
          notes?: string | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          run_id?: string
          gym_number?: number
          leader_name?: string
          variant_used?: string | null
          status?: 'pending' | 'won' | 'lost'
          casualties?: number
          attempts?: number
          notes?: string | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      battle_logs: {
        Row: {
          id: string
          run_id: string
          battle_type: 'gym' | 'trainer' | 'wild' | 'elite_four' | 'champion'
          battle_id: string | null
          team_used: Json | null
          casualties: Json | null
          result: 'won' | 'lost' | 'fled'
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          run_id: string
          battle_type: 'gym' | 'trainer' | 'wild' | 'elite_four' | 'champion'
          battle_id?: string | null
          team_used?: Json | null
          casualties?: Json | null
          result: 'won' | 'lost' | 'fled'
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          run_id?: string
          battle_type?: 'gym' | 'trainer' | 'wild' | 'elite_four' | 'champion'
          battle_id?: string | null
          team_used?: Json | null
          casualties?: Json | null
          result?: 'won' | 'lost' | 'fled'
          notes?: string | null
          created_at?: string
        }
      }
    }
  }
}
